### ISSUE TITLE
Validation goes wrong on prefilled fields

### ISSUE THREAD

**Issue by Resin01** [selbekk/calidation#22]
Hi again

I think I have found a bug.
https://codesandbox.io/s/jz45qyx1x3
If you use CTRL+A and then backspace to delete the content of the email field, you will notice that fields and errors does not update. Therefor you can hit enter to submit and have it submit with success.

The sandbox is updated with the newest version of calidation

**Comment by selbekk** [comment]
Hi! Thanks for filing this! I’ll start looking at this after New Years :-)

**Comment by selbekk** [comment]
Hi @Resin01 - sorry for taking such time to get back to you. I think I found the issue. 

If you change your `<input />` to use `value` instead of `defaultValue`, you should be good.

**Comment by Resin01** [comment]
That is true (if you remember to add an empty onChange to avoid any errors from react).
Just figured it was supposed to work with defaultValue as that is the recommended implementation from react (as I understand it) :)

**Comment by davidbucka** [comment]
First things first: Great package! 🔥

Unfortunately this is not working for me too - not with `value` nor with `defaultValue`

I'm using following code and get the `prop.text` from the parent component:

```ts
const [text, setText] = React.useState("");

React.useEffect(() => {
    setText(props.text);

    return function cleanup() {
        setText("");
    };
});
```

passing `text` down to my `<input>` like this:
```ts
<input
    name="text"
    type="text"
    value={text}
    onChange={e => setText(e.target.value)}
/>
```

**and unless I edit the input the validation fails.**

Btw: I know how the validation works, because i use it already in several other forms
